[package]
name = "load-test"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[[bin]]
name = "load-test"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
enroute-postgres.workspace = true
enroute-signature.workspace = true
enroute-git-core.workspace = true
enroute-git-ingest.workspace = true
enroute-git-http.workspace = true
enroute = { path = "../../crates/server/app" }
enroute-git-cost.workspace = true
enroute-git-retrieve.workspace = true
enroute-git-store.workspace = true
bench-support = { path = "../bench-support" }

object_store.workspace = true
axum.workspace = true
tokio.workspace = true
futures.workspace = true
bytes.workspace = true
sqlx.workspace = true

anyhow.workspace = true
async-trait.workspace = true
reqwest = { workspace = true, features = ["rustls"] }
sha1.workspace = true
clap.workspace = true
tempfile.workspace = true
rlt.workspace = true
rand.workspace = true
