//! The generated wire contract, and nothing else.
//!
//! It depends on no other workspace crate and holds no hand-written logic,
//! which `cargo xtask lint` holds it to by making this an `api` crate: an
//! integrator generates this same contract from `proto/` into another
//! language, so a convenience reachable only from Rust would be a part of
//! the contract they never get, and nothing here would fail to build over it.
//!
//! # Layout
//!
//! One module per protobuf package, nested as the package is named — `prost`
//! lays code out by package, so the file per service is not visible here.

// Said once for the crate: which of these a package trips depends on whether
// it holds a service, so a list per module would churn on every proto edit.
// `missing_docs` is the exception, waived inside the generated modules only —
// it is the rule that notices the hand-written item this crate must not grow.
#![expect(
    unused_qualifications,
    clippy::allow_attributes,
    clippy::allow_attributes_without_reason,
    clippy::as_conversions,
    clippy::default_trait_access,
    clippy::doc_markdown,
    clippy::excessive_nesting,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::too_many_lines,
    reason = "tonic's codegen, which this crate does not get to write"
)]

/// Every file of the contract, encoded, for gRPC reflection to serve.
///
/// Generated bytes, not the hand-written logic this crate must not grow:
/// `protoc --descriptor_set_out` gives another language the same thing.
pub const FILE_DESCRIPTOR_SET: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/enroute_descriptor.bin"));

/// `enroute.common.v1alpha1` — the types both directions of the contract name.
pub mod common {
    /// The generated package.
    ///
    /// No `missing_docs` expectation, unlike the packages below: every field
    /// here is commented in the `.proto`, and stays that way.
    pub mod v1alpha1 {
        tonic::include_proto!("enroute.common.v1alpha1");
    }
}

/// `enroute.api.v1alpha1` — the four services an application drives Enroute with.
pub mod api {
    /// The generated package.
    pub mod v1alpha1 {
        #![expect(missing_docs, reason = "tonic's codegen")]
        tonic::include_proto!("enroute.api.v1alpha1");
    }
}

/// `enroute.hook.v1alpha1` — the payloads Enroute POSTs back to an application.
pub mod hook {
    /// The generated package.
    pub mod v1alpha1 {
        #![expect(missing_docs, reason = "tonic's codegen")]
        tonic::include_proto!("enroute.hook.v1alpha1");
    }
}
