[package]
name = "enroute-git-store"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[lib]
name = "enroute_git_store"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
enroute-git-core.workspace = true
enroute-git-cost.workspace = true
enroute-git-metadata.workspace = true
enroute-git-packfile.workspace = true
object_store.workspace = true
futures.workspace = true
bytes.workspace = true
anyhow.workspace = true
flate2.workspace = true
libdeflater.workspace = true
gix-hash.workspace = true
gix-object.workspace = true
tracing.workspace = true
tokio.workspace = true

[dev-dependencies]
proptest.workspace = true
enroute-git-ingest.workspace = true
enroute-git-test-support.workspace = true
